In [88]:
from selenium import webdriver
import pandas as pd
import requests
driver = webdriver.Chrome()
from bs4 import BeautifulSoup
url="https://www.bewakoof.com/top-wear-for-men"
driver.get(url)

In [125]:
soup = BeautifulSoup(driver.page_source, 'html.parser')
#print(soup.prettify())

In [127]:
container=soup.find('div',id="productGrid")
bewakoof_tshirt=[]
from typing import Text
articals=container.find_all('div',class_="plp-product-card")
for article in articals:
  name=article.find('h3')
  productname=name.get_text()
  name2=article.find('h2')
  productsubname=name2.get_text()
  price=article.find('div',class_="discountedPriceText")
  productprice=price.get_text()
  price2=article.find('div',class_="actualPriceText")
  productactualprice=price2.get_text()
  type1=article.find('div',class_="tag_label_plp")
  if type1 is None:
        producttype=0
  else:
        producttype=type1.get_text()
  rate=article.find('span',class_="clr-shade-3")
  if rate is None:
    productrate=0
  else:
    productrate=rate.get_text()
  bewakoof_tshirt.append([productname,productsubname,productprice,productactualprice,producttype,productrate])

In [128]:
df=pd.DataFrame(bewakoof_tshirt,columns=['productname','productsubname','productprice','productactualprice','producttype','productrate'])
df.to_csv('bewakoof_tshirt.csv')

In [129]:
df

,productname,productsubname,productprice,productactualprice,producttype,productrate
0,bewakoof x dc,Men's Green Batman Graphic Printed Oversized T...,₹749,₹1799,100% COTTON,4.5
1,bewakoof x dc,Men's Black Adam Graphic Printed T-shirt,₹499,₹999,100% COTTON,0
2,Bewakoof®,Men's Black Customizable T-shirt,₹649,₹1199,100% COTTON,0
3,bewakoof x dc,Men's Black Batman Outline Logo T-shirt,₹499,₹1099,100% COTTON,4.5
4,bewakoof x marvel,Men's Black Deadpool Duo Graphic Printed Overs...,₹799,₹1949,100% COTTON,4.5
...,...,...,...,...,...,...
2628,Campus Sutra,Men's Blue All Over Printed Shirt,₹759,₹1899,0,0
2629,FANS ARMY,Men's Black Tokyo Revengers Draken Graphic Pri...,₹499,₹1299,100% COTTON,0
2630,Dillinger,Men's Red & White Striped Oversized T-shirt,₹699,₹999,100% COTTON,0
2631,Campus Sutra,Men's Beige & Brown All Over Printed Shirt,₹759,₹1899,100% COTTON,0
2632,Campus Sutra,Men's Black Shirt,₹674,₹1499,100% COTTON,0